### ISSUE TITLE
[embObjMotionControl] robotInterface hangs if launched with motor switch set to off

### ISSUE THREAD

**Issue by traversaro** [robotology/icub-main#123]
If the user launches the robotInterface with motor switch set to off on the ethernet-based iCubs, it is then impossible to close the `robotInterface` with a Ctrl-C .

**Comment by pattacini** [comment]
@marcoaccame did we solve this problem?

**Comment by marcoaccame** [comment]
Hi @pattacini, ... I think that nobody worked on this issue.

However, I have just tested the behaviour on iCubGenova02 and:

* `yarprobotinterface` can be closed at the third CTRL-C.

![img_2883](https://cloud.githubusercontent.com/assets/7148284/18172883/a055f3a6-7067-11e6-91ca-d766dd12cf1f.JPG)

![img_2884](https://cloud.githubusercontent.com/assets/7148284/18172892/a8cbae54-7067-11e6-9c0c-501c7deffbab.JPG)

**Comment by pattacini** [comment]
@marcoaccame thanks for testing it.

@traversaro with 3 ctrl+c in a row didn't you manage to stop `yarprobotinterface`? In other words, was the module outright stuck?

Though needing 3 stop requests is not graceful, perhaps we can simply get away with that and close the issue. What do you think @traversaro ?

Otherwise, I think we would require to asynchronously _unlock a mutex_ or _exit from a while loop_ that might be there while querying the boards status.

**Comment by traversaro** [comment]
Yes, I opened the issue because it was impossible to close it with 3 Ctrl-C, so I think it can be closed.

**Comment by pattacini** [comment]
Great then.
Closing.
