### ISSUE TITLE
Changing nameserver in icub-cluster.py does not have any effect

### ISSUE THREAD

**Issue by Tobias-Fischer** [robotology/icub-main#168]
Hi all,
I just noticed that one is able to edit all fields (`User`, `Namespace`, `Nameserver node` and the host`Name`s in icub-cluster.py. However, changing the fields does not have any effect, which might cause some confusing situations.
I suggest to either
1) Use the current content of the `Tkinter` `Entry` fields (`x.get()`) instead of the values provided in the configuration file, e.g. change
`cmd = Util.getSshCmd(self.cluster.user, self.cluster.nsNode) + ['icub-cluster-server.sh', ' start']`
in
`cmd = Util.getSshCmd(self.clusterUser.get(), self.clusterNsNode.get()) + ['icub-cluster-server.sh', ' start']`

or

2) Make the fields readonly, e.g. add 
`self.clusterNsNode.config(state='readonly')`
after
`self.clusterNsNode.grid(row=1, column=0, sticky=W)`

or

3)
The tricky thing in 1) would be finding the `Tkinter` `Entry` of the hosts where `icub-cluster-run.sh` is executed. So maybe a combination of 1) and 2) would be best, whereas everything should use the current content of the `Tkinter` `Entry` except of the hostnames, which should be made readonly? I'd be happy to create a pull request for that suggestion.

Best,
Tobias

**Comment by lornat75** [comment]
Your solution is fine, go ahead! thank you

On 30/giu/2015, at 20:23, "Tobias Fischer" <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi all,
I just noticed that one is able to edit all fields (User, Namespace, Nameserver node and the hostNames in icub-cluster.py. However, changing the fields does not have any effect, which might cause some confusing situations.
I suggest to either
1) Use the current content of the Tkinter Entry fields (x.get()) instead of the values provided in the configuration file, e.g. change
cmd = Util.getSshCmd(self.cluster.user, self.cluster.nsNode) + ['icub-cluster-server.sh', ' start']
in
cmd = Util.getSshCmd(self.clusterUser.get(), self.clusterNsNode.get()) + ['icub-cluster-server.sh', ' start']

or

2) Make the fields readonly, e.g. add
self.clusterNsNode.config(state='readonly')
after
self.clusterNsNode.grid(row=1, column=0, sticky=W)

or

3)
The tricky thing in 1) would be finding the Tkinter Entry of the hosts where icub-cluster-run.sh is executed. So maybe a combination of 1) and 2) would be best, whereas everything should use the current content of the Tkinter Entry except of the hostnames, which should be made readonly? I'd be happy to create a pull request for that suggestion.

Best,
Tobias
