### ISSUE TITLE
Verify limit check in cartesian controller with V2 mechanics

### ISSUE THREAD

**Issue by lornat75** [robotology/icub-main#217]
This arose in https://github.com/robotology/icub-support/issues/64

**Comment by pattacini** [comment]
We already checked that in the past for V2 mechanics and the solver is already up-to-date.

What is actually happening on one particular robot is that tendons snap out only on one arm, while everything works smooth on the other arm. Moreover, all the other V2 robots seem to be functioning fine.

This considerations led me to think that there might be some mechanical misalignment/difference on that particular robot and on that particular arm only. That's why I prompted mechies to chip in on this respect.

The fact that mine is still a speculation would suggest to keep https://github.com/robotology/icub-support/issues/64 open for investigation.

@lornat75 @super-ste @bhigy
