### ISSUE TITLE
FirmwareUpdater commands disabled

### ISSUE THREAD

**Issue by davidetome** [robotology/icub-main#407]
launching the firmwareupdater GUI all commandButtons are disabled by default.

@marcoaccame @ale-git

**Comment by marcoaccame** [comment]
Hi @davidetome, you have probably used `FirmwareUpdater` in a new robot where it could not find the `firmwareupdater.ini` file it needs.

Here is what happens if I remove the  `firmwareupdater.ini` file from my system (not a robot): all buttons are disabled.

```
acemor@ubuntu:~$ FirmwareUpdater 
Using default address  10.0.1.104
[DEBUG]Using default address  10.0.1.104 
Using default port  3333
[DEBUG]Using default port  3333 
Usage:  FirmwareUpdater  --port n --address xxx.xxx.xxx.xxx

||| clearing context
||| adding context [firmwareUpdater]
||| configuring
||| default config file specified as firmwareupdater.ini
||| checking [/home/acemor/firmwareupdater.ini] (pwd)
||| checking [/home/acemor/.config/yarp/robots/iCubGenova02] (robot YARP_CONFIG_HOME)
||| checking [/home/acemor/.local/share/yarp/robots/iCubGenova02] (robot YARP_DATA_HOME)
||| checking [/etc/xdg/xdg-ubuntu/yarp/robots/iCubGenova02] (robot YARP_CONFIG_DIRS)
||| checking [/usr/share/upstart/xdg/yarp/robots/iCubGenova02] (robot YARP_CONFIG_DIRS)
||| checking [/etc/xdg/yarp/robots/iCubGenova02] (robot YARP_CONFIG_DIRS)
||| checking [/home/acemor/robotology/yarp/build-pc104/share/yarp/robots/iCubGenova02] (robot YARP_DATA_DIRS)
||| checking [/home/acemor/robotology/icub-main/build-pc104/share/iCub/robots/iCubGenova02] (robot YARP_DATA_DIRS)
||| found /home/acemor/robotology/icub-main/build-pc104/share/iCub/robots/iCubGenova02
||| checking [/home/acemor/robotology/yarp/build-pc104/share/yarp/config/path.d] (robot path.d YARP_DATA_DIRS)
||| checking [/home/acemor/robotology/icub-main/build-pc104/share/iCub/config/path.d] (robot path.d YARP_DATA_DIRS)
||| checking [/home/acemor/robotology/icub-main/build-pc104/share/iCub/robots/iCubGenova02/firmwareupdater.ini] (robot)
||| checking [/home/acemor/.config/yarp/contexts/firmwareUpdater] (context YARP_CONFIG_HOME)
||| checking [/home/acemor/.local/share/yarp/contexts/firmwareUpdater] (context YARP_DATA_HOME)
||| checking [/etc/xdg/xdg-ubuntu/yarp/contexts/firmwareUpdater] (context YARP_CONFIG_DIRS)
||| checking [/usr/share/upstart/xdg/yarp/contexts/firmwareUpdater] (context YARP_CONFIG_DIRS)
||| checking [/etc/xdg/yarp/contexts/firmwareUpdater] (context YARP_CONFIG_DIRS)
||| checking [/home/acemor/robotology/yarp/build-pc104/share/yarp/contexts/firmwareUpdater] (context YARP_DATA_DIRS)
||| checking [/home/acemor/robotology/icub-main/build-pc104/share/iCub/contexts/firmwareUpdater] (context YARP_DATA_DIRS)
||| checking [/home/acemor/.config/yarp/firmwareupdater.ini] (YARP_CONFIG_HOME)
||| checking [/home/acemor/.local/share/yarp/firmwareupdater.ini] (YARP_DATA_HOME)
||| checking [/etc/xdg/xdg-ubuntu/yarp/firmwareupdater.ini] (YARP_CONFIG_DIRS)
||| checking [/usr/share/upstart/xdg/yarp/firmwareupdater.ini] (YARP_CONFIG_DIRS)
||| checking [/etc/xdg/yarp/firmwareupdater.ini] (YARP_CONFIG_DIRS)
||| checking [/home/acemor/robotology/yarp/build-pc104/share/yarp/firmwareupdater.ini] (YARP_DATA_DIRS)
||| checking [/home/acemor/robotology/icub-main/build-pc104/share/iCub/firmwareupdater.ini] (YARP_DATA_DIRS)
||| did not find firmwareupdater.ini
yarp: cannot read from firmwareupdater.ini

```

![image](https://cloud.githubusercontent.com/assets/7148284/21608863/6337904c-d1bf-11e6-937b-e06c3a74a29e.png)


Instead, if I add a `firmwareupdater.ini` file here is what happens.

```
acemor@ubuntu:~$ mv firmwareupdater.ini.removed firmwareupdater.ini
acemor@ubuntu:~$ FirmwareUpdater 
Using default address  10.0.1.104
[DEBUG]Using default address  10.0.1.104 
Using default port  3333
[DEBUG]Using default port  3333 
Usage:  FirmwareUpdater  --port n --address xxx.xxx.xxx.xxx

||| clearing context
||| adding context [firmwareUpdater]
||| configuring
||| default config file specified as firmwareupdater.ini
||| checking [/home/acemor/firmwareupdater.ini] (pwd)
||| found /home/acemor/firmwareupdater.ini
"CFW2" - "0"
"CFW2" - "1"
"ESD" - "5"
"ESD" - "6"
"ETH" - "eth1"

```
 
![image](https://cloud.githubusercontent.com/assets/7148284/21608919/d3dd9b34-d1bf-11e6-8f11-2ad08eeae713.png)

As you can see the button `Discover` is now enabled.



FirmwareUpdater is still in the devel branch of icub-main and I have configured for its use only the robots which are in the lab in Genova (or rather: iCubGenova04 and iCubGenova02). 

I still have to prepare proper how-to-use documentation and the .ini files for all the robots. I will do it soon and in any case before next merge of devel into master, which the moment in which the new features will go to other robots as well.

In the meantime, if you want to test `FirmwareUpdater` on a new robot, you have to prepare the .ini file by yourself in the following way.

* Prepare a `firmwareupdater.ini` file similar to the following (used for iCubGenova02) 
 ```
[DRIVERS]
ETH    "eth1"
CFW2   "0"
CFW2   "8"
```
* Place the `firmwareupdater.ini` file into the same folder where `yarprobotinterface.ini` goes. This file will eventually be placed into the robot-configurations repository and installed with all other required files.
* As an alternative of placing the `firmwareupdater.ini` file into some strange folder you can use the `--from file.ini` option.

After the environment is ready:
1 .Launch `FirmwareUpdater` (or also `FirmwareUpdater --from thefileiwant2use.ini`. There will be three rows with the specified drivers. 
2. Highlight the row you want and then press button `Discover`
3. For further action highlight or select the found boards.
4. In case of doubts use the contextual menu activated by placing the mouse on a specific button / icon for more than 1 sec.
