### ISSUE TITLE
Unit tests for motor control board

### ISSUE THREAD

**Issue by lornat75** [robotology/icub-main#64]
It has been discussed several times that we need to implement a set of tests for the robot. In particular it is important to implement a set of tests for motor control board. Test should be runnable on the real robot and the simulator.

The icub-main already contains an unit-test like infrastructure for testing that was implemented for this purpose.

@traversaro @randaz81 @arocchi @barbalberto @EnricoMingo

**Comment by barbalberto** [comment]
Relate to the velocityControllerTest, that test was initially done to debug a weird movement on a shoulder if I remember correctly. Then, to avoid losing it, it was placed in the repo in that folder because it was the place it could fit better, but it was done for a specific issue and not written with thhe idea to be compliant with the iCubTest infrastructure in mind. 

The idea was to generate different velocity profiles (sinusoidal, trapezoidal or whatever) to choose from using a config file, in order to test the motor on different conditions.
It reads joint limits at startup, it moves the joint to a safe position and then start the velocity control routine, then at the ctrl+c it goes back to homing again.

Right now only the sinusoidal profile is implemented, can control 1 joint at time, and it simply sends trajectories, does not check for feedback (it does check for homing position to be reached).

We can read encoders and velocities from encoder to compare with the references and fit it into iCubTest infrastructure if you think it is useful.

**Comment by lornat75** [comment]
Maybe this could become a test on the accuracy with which a joint is supposed to track a reference (cumulative error). It could be a way to ensure a certain level of quality in tuning gains.

**Comment by barbalberto** [comment]
Yes, in the debug process the comparison was done by hand.
I'd love to have such a test completed, it will also make an objective way to compare performances of robot using different firmware and/or different mechanichs.
