### ISSUE TITLE
Launching robotInterface and iCubStartup modules simultaneously

### ISSUE THREAD

**Issue by pattacini** [robotology/icub-main#66]
It would be worth devising a way to restore the old good feature we used to have along with the superseded `iCubInterface` back inside the new `robotInterface`, which was regarded with the possibility to launch at once all the modules of the `iCubStartup` application.

**Past**
Components such as `iKinGazeCtrl`, `iKinCartesianSolver`, `fingersTuner`, `wholeBodyDynamics` were able to continuously query about the existence of motor ports before going further with their own initialization. Since those ports were made available by the `iCubInterface` only as the very last operation, everything was running smoothly. As result, the user was able to press the overall start button of the `iCubStartup` application.

**Present**
`robotInterface` opens up motor ports not at the end of its start-up phase, hence the downstream modules believe they can proceed anyway while of course that's not true.

Is there any way to address this issue with the new software?
Maybe the `PolyDriver::open()` at the client side could exchange some message with the remote in order to be notified when `robotInterface` is really ready. I think now it returns `true` as soon as the connection with motor port is successful.

**Comment by pattacini** [comment]
Do we have any update on that? Is there any progress?
Solving this issue will facilitate a lot our everyday life.

**Comment by barbalberto** [comment]
I was thinking about a solution but it is trickier then I thought at the beginning.
The problem now is that inside the wrapper, the attach functions also opens the yarp ports.

The sequence in the robotInterface now is:
  - open all devices
  - attach wrappers + open ports  (port are up and running with uncalibrated robot)
  - calibrate (requires wrappers on)

The proper way of dealing with this would be, imho to split up the attach step from the open of the ports and have this start-up sequence:
  - open all devices
  - attach wrappers (ports not opened yet)
  - calibrate (it will work because calibbrators are internal in the robotInterface and they uses an attach method as well)
  - open ports when calibration is ended.

In order to do this a change in the wrapper interface and in the configuration files will be required, and I fear issue in back compatibility since the wrapper will not open the ports anymore without an explicit extern request. Simulator should not have problems because they uses the --subdevice param, but other uses of the wrappers will face problem unless we can find a trick to ensure the compatibility.

Just brainstorming:
Maybe creating a "management"  interface will do the trick, we can put in this interface methhods like start/stop/abort  (the latter is foreseen by the robotInterface but not implemented in any device) and maybe have a config param default off to use it or fallback on compatibility mode.

**Comment by pattacini** [comment]
thanks @barbalberto 
Changing the behavior of `robotInterface` only would be great, if possible, perhaps by means of that interface you have in mind. This way we could avoid any impact on present code opening up motor drivers.

@lornat75 any comment?

**Comment by lornat75** [comment]
Looks like a plausible solution if we use it in yarpmanger and not in the cartesian interfaces/devices. I don't like the idea of introducing this dependency in those modules, it could be ok if the dependency ends up in an xml file only.

However I would like to see if we can achieve the same behavior without an administrative interface.

**Comment by lornat75** [comment]
After speaking with @apaikan, @drdanz, @barbalberto we can implement this functionality in robotinterface and synchronize the execution of the xml.

**Comment by pattacini** [comment]
cool :+1:

**Comment by randaz81** [comment]
what is the solution? about "we can implement this functionality in
robotinterface" I don't like at all the idea of opening ports after the
calibration (mentioned 4 posts ago). They should be operative from the
beginning, i.e. when the wrapper is started.

2015-02-18 12:40 GMT+01:00 Ugo Pattacini <notifications@github.com>:

**Comment by pattacini** [comment]
As far as I've understood, the motor ports will be opened as usually, but the `robotInterface` will open up a service port where notifications on the internal states will be provided, so that `yarpmanager` can query it and postpones the launch of down-stream modules (i.e. `iKinCartesianSolver`, `wholeBodyDynamics` ...)

**Comment by lornat75** [comment]
@randaz81, it is how @pattacini describes it. robotinterface already opens a port it is just a matter of implementing the messages that provides the status, and modify yarpmanager to handle it.

**Comment by drdanz** [comment]
I added an RPC port to robotInterface at `/robotInterface` and added a
few commands. I used IDLs, so you can easily get the help from the port.

The command you want to use is probably `is_ready`.

@apaikan already implemented the RPC request for querying the internal state of a module using yarpmanager. It can be done using something like this in the xml:

```xml
<module>
    <name> my-module </name>
    <dependencies>	
	<port timeout="5.0" request="ready" reply="yes"> /a-port/rpc:i </port>
    </dependencies>
</module>
```

**Comment by pattacini** [comment]
Great! Thanks @apaikan @drdanz 
I'll test these changes asap and let you know.

**Comment by pattacini** [comment]
It works like a charm, thanks!
Btw, I've spotted a strange return code from `robotInterface` in the `yarpmanager` log:

```
[ERR] (iCubStartup) received wrong reply from resource /robotInterface for request is_ready. (expected=[ok], received=[FAIL])
[ERR] (iCubStartup) received wrong reply from resource /robotInterface for request is_ready. (expected=[ok], received=[FAIL])
[ERR] (iCubStartup) received wrong reply from resource /robotInterface for request is_ready. (expected=[ok], received=[OK])
[ERR] (iCubStartup) received wrong reply from resource /robotInterface for request is_ready. (expected=[ok], received=[fail])
[ERR] (iCubStartup) received wrong reply from resource /robotInterface for request is_ready. (expected=[ok], received=[FAIL])
[ERR] (iCubStartup) received wrong reply from resource /robotInterface for request is_ready. (expected=[ok], received=[fail])
[ERR] (iCubStartup) received wrong reply from resource /robotInterface for request is_ready. (expected=[ok], received=[fail])
...
[ERR] (iCubStartup) received wrong reply from resource /robotInterface for request is_ready. (expected=[ok], received=[fail])
```

The third line has an "[OK]" (upper-case), while the robot was still clearly warming up... However, given the upper-case it was not recognized as a ready-to-go.

**Comment by pattacini** [comment]
Also, the `[ERR]` messages could be turned into `[WARN]` messages for this kind of notification; what do you think @apaikan?

**Comment by drdanz** [comment]
That's weird, it never happened when I tried manually. Perhaps some race condition? I did not protect the phase with a mutex since all messages are read only and it is changed only by one thread.
Also I wonder why some fails are uppercase `[FAIL]` and some are lowercase `[fail]`.
Perhaps both the uppercase messages are received in an inconsistent status

I agree that the message should not be an error, perhaps not even a warning... Also "received wrong reply" looks wrong.

Perhaps yarpmanager should have 2 expected messages (ready and not ready) and print a warning only when a different message is received, and an info message while it is waiting.

**Comment by pattacini** [comment]
I agree with @drdanz :+1:

**Comment by apaikan** [comment]
agreed! 

`[INFO]` can be a solution! up to now, we did not have any situation where manager should wait on an iterative action and in the manager whatever happens, was somehow atomic: Succeed or failed! 

For a quick fix, I have changed the message status to the [Warning] and change the message to `waiting for the expected reply from resource ...`! 

Btw, @pattacini : Does it print out many failure messages while waiting for the expected reply from the `robotInterface`?

**Comment by apaikan** [comment]
Btw, this line is a bit strange: 
`[ERR] (iCubStartup) received wrong reply from resource /robotInterface for request is_ready. (expected=[ok], received=[OK])` 

The check on the reply should be case insensitive!  Let me check for that!

**Comment by pattacini** [comment]
@apaikan yep, there were many, since in that particular xml script we have several modules waiting for the `robotInterface`.

**Comment by pattacini** [comment]
anyway, that script is operative on `Bluey`.
