### ISSUE TITLE
When a joint goes in HF, errors like `positionMoveRaw: skipping command` flood the logger

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/icub-main#768]
### Bug description

When writing simple applications to control the robot, we are used to sending commands to joints without checking the current control mode. See for example https://github.com/robotology/icub-tutorials/blob/23ac25487d5a872030b82b38a28eb44b2cb3bda3/src/motorControlBasic/tutorial_arm.cpp#L129

This is because we usually set the desired control mode only once, during the initialization phase, and during the control loop we simply get some measurement, and we set the references to the joints.

It may happen though, that some joint goes in HF after the startup. This happens quite easily with the hands. After that, the logger gets quickly filled up with messages like:
```
<ERROR> velocityMoveRaw: skipping command because  BOARD left_arm-eb26-j12_15 (IP 10.0.1.26)   joint  2  is not in VOCAB_CM_VELOCITY mode
```
Since the top level application usually does not check for the control mode at each control loop, it keeps sending references to the joint, producing errors like the above. Since the control loop is usually at 100Hz, this will saturate the logger quite easily, losing the possibility to check other errors.  

cc @pattacini @marcoaccame 

### Steps to reproduce

It should be enough to run the tutorial https://github.com/robotology/icub-tutorials/tree/23ac25487d5a872030b82b38a28eb44b2cb3bda3/src/motorControlBasic on the robot and change the control mode of the controlled joints to something different from ``Position`` and ``Idle``.

### Expected behavior

The errors of https://github.com/robotology/icub-main/blob/601af527248f16c73e3d353bf9bdac0fa47b3d9c/src/libraries/icubmod/embObjMotionControl/embObjMotionControl.cpp#L2224, https://github.com/robotology/icub-main/blob/601af527248f16c73e3d353bf9bdac0fa47b3d9c/src/libraries/icubmod/embObjMotionControl/embObjMotionControl.cpp#L1897, and https://github.com/robotology/icub-main/blob/601af527248f16c73e3d353bf9bdac0fa47b3d9c/src/libraries/icubmod/embObjMotionControl/embObjMotionControl.cpp#L4106

should be limited in time, eventually sending the error only once, and sending it again when the control mode changes.

**Comment by pattacini** [comment]
This is not a bug, but rather more a feature request, I'd say.

In my opinion, the high-level SW should be responsible somehow for checking the status of the boards. We do this for example in the Cartesian and Gaze controller.

However, due to some other limitations (see https://github.com/robotology/community/discussions/558) that may turn out to be severe in certain conditions, I reckon we could come up with a kind of workaround.

Regarding the workaround strategy below

>should be limited in time, eventually sending the error only once, and sending it again when the control mode changes.

I wouldn't rule out yet the choice of keeping triggering the error but at a much lower frequency. We'd need to ponder all the possibilities.

**Comment by pattacini** [comment]
To illustrate what I have in mind, I've fast-prototyped the handling logic in Stateflow.

| |
| :---: |
| <img width="847" alt="model-1" src="https://user-images.githubusercontent.com/3738070/137967549-1ce9bb60-bbf6-4000-93a9-3398ba54bb55.png"> |
| The model with the input and the outputs |
|<img width="1073" alt="model-2" src="https://user-images.githubusercontent.com/3738070/137967558-ba965681-94cf-4a8e-bd8c-82d64438a02e.png"> |
| A closer look at the FSM chart composed of 2 parallel subcharts |

Essentially, the FSM receives as input a boolean that is `1` when an error message is being triggered and `0` otherwise and yields as output a corresponding boolean with the same logic that undergoes however a sort of smart down-sampling plus a counter that tells us how many original errors have been raised in a given temporal window.

The handler is composed of two parallel charts:
- one is devoted to evaluating the number of errors triggered in a given temporal window (default = 1 sec)
- one is the actual handler implementing the logic below:
  - If the frequency of the errors is above a threshold, then it triggers the output only each second (i.e., same lapse as above).
  - Otherwise, output = input.  

We have only 2 params:
- The temporal window used to evaluate the frequency of the input errors and to carry out down-sampling at the output stage.
- The errors threshold detected in the window above which triggers down-sampling (default = 5).

Here's below a typical outcome where it's shown how the output follows the input only within the initial window that serves to evaluate the occurrence of the errors. After that, the output gets triggered only in single instances.

<img width="1217" alt="graph" src="https://user-images.githubusercontent.com/3738070/137968954-0d48608c-f74a-4af2-a57b-bf47c296f7a4.png">

The FSM can be obviously used to generate code.

---

You can play with the model yourself: [error_downsampler.zip](https://github.com/robotology/icub-main/files/7375833/error_downsampler.zip).

**Comment by pattacini** [comment]
@mfussi66 and @davidetome are working on this in https://github.com/mfussi66/icub-main/tree/devel.

**Comment by pattacini** [comment]
Done in #770.
