### ISSUE TITLE
Removing  the definition file for skin error codes from src/libraries/icubmod/motionControlLib.

### ISSUE THREAD

**Issue by lornat75** [robotology/icub-main#81]
This is raised in #80.

Possible solution is to move skin error codes from motionControlLib to firmwareShared.

@barbalberto, @randaz81, @JoErNanO

**Comment by JoErNanO** [comment]
Instead of something generic like firmwareShared, what about creating a dedicated skin* directory in `libraries/icubmod/`? 

Moreover, come to think about it, the definitions inside skinDiagnostics file should be split in two. The `struct DetectedError` is used by both canBus/embObjSkin alone, whilst the ` struct SkinErrorCode` by the skinManager alone. This separation of concerns will break the dependency problem caused by the skinManager depending on something on which two icubmod libraries also depend. This was the original intended design, changed by @barbalberto [here](https://github.com/robotology/icub-main/commit/3b2317015701887d3815535f9b509180ef6f5893#commitcomment-8655341).
