### ISSUE TITLE
Fix the motor temperature spike filtering  in embObjMotionControl

### ISSUE THREAD

**Issue by valegagge** [robotology/icub-main#959]
### Bug description

In embObjMotionControl, a temperature monitor has been implemented to provide a warning to the user when the temperature goes beyond the warning threshold defined in the configuration file.
Since the motor temperature reading suffers from disturbance there are some spikes that have not be take in consideration in the check of the warning threshold.

In addition, the current fw sends some negative values to encode some error cases. Also, this should be removed from the warning check.

### Steps to reproduce

Just read the motor temperature. (In some motors the readings are noisier than others)

### Expected behavior

In the log, there are any warnings related to the spikes of temperature

**Comment by valegagge** [comment]
Just a tip: for debugging and making the work, you can create an ad hoc fw that sometimes sends a spike.
Of course, the final test has to be done on the robot

**Comment by MSECode** [comment]
After developing a first version of the filtering in the sw I've tested it by generating synthetic data with the aim of simulating a continuous rising of the temperatures with a pyramidal pattern. Basically, starting from 0 degree I've then risen the temperature of about 10 degree, so that the threshold between temperature at time interval `i` and `i-1` (20 degree) it is not overcome. Then, after some steps I've instead increment the temperature to a higher value (around 110/120 degree in order to simulate a spike). And finally I've decreased again the temperature value.
Part of the described behavior is shown in this image

![image](https://github.com/robotology/icub-main/assets/77933235/ae62821e-714c-4f78-a615-635960a90c47)

Doing so, and looking at the logs of the YRI, it is possible to see that we do not have any warning related to the generated spike but the warning are just related to the overcoming of the warning temperature limit (set now to 40 degree just for test purposes) when the delta between current and previous temperature is lower than a defined threshold.

![image](https://github.com/robotology/icub-main/assets/77933235/a752908f-635b-4f3f-adf8-64738bc549a1)


cc: @valegagge

**Comment by MSECode** [comment]
/reminder May, 21, 2024

@valegagge @MSECode

**Comment by MSECode** [comment]
## WIP
 my branch 

![Screenshot from 2024-05-21 19-33-08](https://github.com/robotology/icub-main/assets/77933235/dae5d901-276a-4eb0-9fcd-9e451f6252cc)

**Comment by MSECode** [comment]
PR opened here:

https://github.com/robotology/icub-main/pull/961

**Comment by pattacini** [comment]
PR merged ✅ 
Probably, this issue can be closed as complete.

cc @MSECode @valegagge
